FROM node:20-alpine as build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

RUN npm run build:admin

FROM nginx:alpine

COPY --from=build /app/dist-admin /usr/share/nginx/html

RUN mv /usr/share/nginx/html/index-admin.html /usr/share/nginx/html/index.html 2>/dev/null || true

COPY nginx-admin.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
