#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
北京植物园完整植物数据库生成脚本
包含200+种详细的植物数据和真实图片URL
"""

import json
import os
from datetime import datetime
from dataclasses import dataclass, field, asdict
from typing import List, Dict

PLANT_DATABASE = [
    {
        "id": "plant_001",
        "name_cn": "玉兰",
        "name_latin": "Magnolia denudata",
        "family": "木兰科",
        "genus": "木兰属",
        "common_names": ["白玉兰", "望春花", "应春花"],
        "description": "玉兰是中国著名的早春花木，花先叶开放，洁白如玉，香气馥郁。",
        "detailed_description": "玉兰是落叶乔木，高达25米，胸径1米，枝广展形成宽阔的树冠。树皮深灰色，粗糙开裂。",
        "morphology": "落叶乔木，树冠卵形或近球形。叶互生，倒卵形，先端宽圆，具突尖。花先叶开放，单生枝顶，白色，芳香。",
        "habitat": "喜阳光充足环境，稍耐阴，喜温暖湿润气候。",
        "distribution": "中国特产，分布于江西、浙江、湖南、贵州等地，现全国各地广泛栽培。",
        "garden_zones": ["木兰园", "树木园"],
        "protection_status": "",
        "iucn_status": "LC (无危)",
        "uses": ["观赏", "药用", "用材"],
        "medicinal_uses": "花蕾入药，能散风寒、通鼻窍。",
        "ornamental_value": "早春开花，花大洁白，香气浓郁，是著名的观赏花木。",
        "ecological_value": "对有害气体有一定抗性。",
        "cultural_significance": "玉兰花是上海市市花，象征纯洁和高雅。",
        "flowering_period": "2-3月",
        "fruiting_period": "8-9月",
        "light_requirements": "喜光，稍耐阴",
        "water_requirements": "喜湿润",
        "soil_preference": "深厚肥沃的酸性土壤",
        "growth_rate": "中等",
        "lifespan": "可达百年",
        "max_height": "25米",
        "max_width": "树冠幅可达20米",
        "leaf_type": "单叶互生，倒卵形",
        "flower_color": "花白色，有香气",
        "fruit_color": "聚合果，圆柱形",
        "ppbc_id": "46386",
        "image_source": "ppbc"
    },
    {
        "id": "plant_002",
        "name_cn": "紫玉兰",
        "name_latin": "Magnolia liliflora",
        "family": "木兰科",
        "genus": "木兰属",
        "common_names": ["木兰", "辛夷", "木笔"],
        "description": "紫玉兰是著名的观赏花木，花紫色或紫红色，春季开放。",
        "detailed_description": "紫玉兰是落叶灌木，高达3-5米，常丛生。树皮灰褐色，小枝绿紫色或淡褐紫色。",
        "morphology": "落叶灌木，常丛生。叶椭圆状倒卵形或倒卵形，先端急尖或渐尖。花先叶开放或与叶同放，瓶形，直立于粗壮、被毛的花梗上。",
        "habitat": "喜温暖湿润环境，稍耐阴。",
        "distribution": "中国特产，分布于湖北、四川、云南等地，现广泛栽培。",
        "garden_zones": ["木兰园"],
        "protection_status": "",
        "iucn_status": "",
        "uses": ["观赏", "药用"],
        "medicinal_uses": "花蕾入药，能散风寒、通鼻窍。",
        "ornamental_value": "春季开花，花色艳丽，是著名的观赏花木。",
        "ecological_value": "",
        "cultural_significance": "",
        "flowering_period": "3-4月",
        "fruiting_period": "8-9月",
        "light_requirements": "喜光，稍耐阴",
        "water_requirements": "喜湿润",
        "soil_preference": "深厚肥沃的土壤",
        "growth_rate": "中等",
        "lifespan": "",
        "max_height": "5米",
        "max_width": "",
        "leaf_type": "单叶互生，椭圆状倒卵形",
        "flower_color": "花紫色或紫红色",
        "fruit_color": "聚合果，圆柱形",
        "ppbc_id": "148075",
        "image_source": "ppbc"
    },
    {
        "id": "plant_003",
        "name_cn": "二乔玉兰",
        "name_latin": "Magnolia soulangeana",
        "family": "木兰科",
        "genus": "木兰属",
        "common_names": ["苏郎木兰", "朱砂玉兰"],
        "description": "二乔玉兰是白玉兰和紫玉兰的杂交种，花大色艳，是著名的观赏花木。",
        "detailed_description": "二乔玉兰是落叶小乔木，高6-10米。小枝无毛。叶倒卵形，先端短急尖。",
        "morphology": "落叶小乔木，叶纸质，倒卵形，先端短急尖。花先叶开放，浅红色至深红色，花被片6-9片。",
        "habitat": "喜温暖湿润环境，适应性强。",
        "distribution": "杂交种，全国各地广泛栽培。",
        "garden_zones": ["木兰园"],
        "protection_status": "",
        "iucn_status": "",
        "uses": ["观赏"],
        "medicinal_uses": "",
        "ornamental_value": "早春开花，花大色艳，是著名的观赏花木。",
        "ecological_value": "",
        "cultural_significance": "",
        "flowering_period": "3-4月",
        "fruiting_period": "9-10月",
        "light_requirements": "喜光",
        "water_requirements": "喜湿润",
        "soil_preference": "深厚肥沃的土壤",
        "growth_rate": "中等",
        "lifespan": "",
        "max_height": "10米",
        "max_width": "",
        "leaf_type": "单叶互生，倒卵形",
        "flower_color": "花淡紫色，里面白色",
        "fruit_color": "聚合果，卵圆形",
        "ppbc_id": "46387",
        "image_source": "ppbc"
    },
    {
        "id": "plant_004",
        "name_cn": "望春玉兰",
        "name_latin": "Magnolia biondii",
        "family": "木兰科",
        "genus": "木兰属",
        "common_names": ["望春花", "华中木兰"],
        "description": "望春玉兰是中国特有树种，早春开花，是重要的药用和观赏植物。",
        "detailed_description": "望春玉兰是落叶乔木，高达12米，胸径达1米。树皮淡灰色，光滑。",
        "morphology": "落叶乔木，叶长圆状披针形或卵状披针形，先端急尖或渐尖。花先叶开放，花被片9，外轮3片紫红色。",
        "habitat": "喜阳光充足环境，稍耐阴。",
        "distribution": "中国陕西、甘肃、河南、湖北、四川等地。",
        "garden_zones": ["木兰园"],
        "protection_status": "",
        "iucn_status": "",
        "uses": ["观赏", "药用", "油料"],
        "medicinal_uses": "花蕾入药，能散风寒、通鼻窍。",
        "ornamental_value": "早春开花，花色艳丽，是优良的园林观赏树种。",
        "ecological_value": "",
        "cultural_significance": "",
        "flowering_period": "3月",
        "fruiting_period": "9月",
        "light_requirements": "喜光",
        "water_requirements": "中等",
        "soil_preference": "深厚肥沃的土壤",
        "growth_rate": "中等",
        "lifespan": "",
        "max_height": "12米",
        "max_width": "",
        "leaf_type": "单叶互生，长圆状披针形",
        "flower_color": "花白色，基部带紫红色",
        "fruit_color": "聚合果，圆柱形",
        "ppbc_id": "46385",
        "image_source": "ppbc"
    },
    {
        "id": "plant_005",
        "name_cn": "鹅掌楸",
        "name_latin": "Liriodendron chinense",
        "family": "木兰科",
        "genus": "鹅掌楸属",
        "common_names": ["马褂木", "双飘树"],
        "description": "鹅掌楸是中国特有的珍稀树种，叶形奇特如马褂，是国家二级保护植物。",
        "detailed_description": "鹅掌楸是落叶大乔木，高达40米，胸径1米以上。树皮黑褐色，纵裂。",
        "morphology": "落叶大乔木，叶马褂形，先端平截或微凹，两侧各具1裂片。花单生枝顶，杯状，黄绿色。",
        "habitat": "喜温暖湿润环境，喜深厚肥沃的土壤。",
        "distribution": "中国长江流域以南，分布于陕西、安徽、浙江、江西、福建、湖北、湖南、广西、四川、贵州、云南等地。",
        "garden_zones": ["木兰园", "珍稀濒危植物区"],
        "protection_status": "国家二级保护",
        "iucn_status": "VU (易危)",
        "uses": ["观赏", "用材", "科研"],
        "medicinal_uses": "树皮入药，能祛风除湿、散寒止咳。",
        "ornamental_value": "叶形奇特，花大美丽，是世界著名的观赏树种。",
        "ecological_value": "中国特有树种，对研究植物区系有重要科学价值。",
        "cultural_significance": "",
        "flowering_period": "5月",
        "fruiting_period": "9-10月",
        "light_requirements": "喜光",
        "water_requirements": "喜湿润",
        "soil_preference": "深厚肥沃的酸性土壤",
        "growth_rate": "快",
        "lifespan": "",
        "max_height": "40米",
        "max_width": "",
        "leaf_type": "单叶互生，马褂形",
        "flower_color": "花黄绿色，形似郁金香",
        "fruit_color": "聚合果，纺锤形",
        "ppbc_id": "46364",
        "image_source": "ppbc"
    },
    {
        "id": "plant_006",
        "name_cn": "水杉",
        "name_latin": "Metasequoia glyptostroboides",
        "family": "杉科",
        "genus": "水杉属",
        "common_names": ["水桫", "活化石"],
        "description": "水杉是世界上珍稀的孑遗植物，有'活化石'之称。",
        "detailed_description": "水杉是落叶乔木，高达35米，胸径达2.5米。树干基部常膨大。",
        "morphology": "落叶大乔木，叶线形，在侧枝上排成羽状，冬季与枝一同脱落。球果下垂，近四棱状球形。",
        "habitat": "喜温暖湿润气候，适应性强。",
        "distribution": "中国特产，分布于四川石柱县及湖北利川县等地。",
        "garden_zones": ["珍稀濒危植物区", "树木园"],
        "protection_status": "国家一级保护",
        "iucn_status": "CR (极危)",
        "uses": ["用材树种", "观赏树种", "科研价值"],
        "medicinal_uses": "",
        "ornamental_value": "树姿优美，叶色翠绿，秋季叶色变黄，是优良的庭园观赏树种。",
        "ecological_value": "水杉林具有良好的水源涵养功能。",
        "cultural_significance": "水杉的发现改写了植物学历史。",
        "flowering_period": "2月下旬至3月上旬",
        "fruiting_period": "10-11月",
        "light_requirements": "喜光",
        "water_requirements": "喜湿润",
        "soil_preference": "酸性黄壤土",
        "growth_rate": "中等偏快",
        "lifespan": "可达600年以上",
        "max_height": "35米",
        "max_width": "树冠幅10-15米",
        "leaf_type": "线形叶，冬季脱落",
        "flower_color": "雌雄同株，雄球花黄色",
        "fruit_color": "球果熟时深褐色",
        "ppbc_id": "46929",
        "image_source": "ppbc"
    },
    {
        "id": "plant_007",
        "name_cn": "银杏",
        "name_latin": "Ginkgo biloba",
        "family": "银杏科",
        "genus": "银杏属",
        "common_names": ["白果树", "公孙树", "鸭脚子"],
        "description": "银杏是现存最古老的种子植物之一，有'活化石'之称。",
        "detailed_description": "银杏是落叶大乔木，高可达40米，胸径可达4米。叶扇形，有长柄。",
        "morphology": "落叶大乔木，树冠幼时圆锥形，老时广卵形。叶扇形，上缘呈波状缺刻。雌雄异株。",
        "habitat": "喜温暖湿润气候，适应性强。",
        "distribution": "中国特产，野生状态仅见于浙江天目山。",
        "garden_zones": ["裸子植物区", "树木园"],
        "protection_status": "国家一级保护",
        "iucn_status": "EN (濒危)",
        "uses": ["药用", "食用", "观赏", "用材", "科研"],
        "medicinal_uses": "银杏叶提取物用于治疗心脑血管疾病，种子入药可润肺止咳。",
        "ornamental_value": "树姿雄伟壮丽，叶形奇特优美，秋季叶色金黄。",
        "ecological_value": "银杏树寿命长，抗污染能力强。",
        "cultural_significance": "银杏在中国文化中象征长寿和坚韧。",
        "flowering_period": "3-4月",
        "fruiting_period": "9-10月",
        "light_requirements": "强阳性",
        "water_requirements": "耐旱",
        "soil_preference": "酸性至中性土壤",
        "growth_rate": "慢",
        "lifespan": "可达3000年以上",
        "max_height": "40米",
        "max_width": "树冠幅可达30米",
        "leaf_type": "扇形叶",
        "flower_color": "雄球花淡黄色，雌球花淡绿色",
        "fruit_color": "种子成熟时黄色或橙黄色",
        "ppbc_id": "46926",
        "image_source": "ppbc"
    },
    {
        "id": "plant_008",
        "name_cn": "白皮松",
        "name_latin": "Pinus bungeana",
        "family": "松科",
        "genus": "松属",
        "common_names": ["白骨松", "三针松", "蟠龙松"],
        "description": "白皮松是中国特有树种，树皮呈白色或灰白色，成不规则薄片脱落。",
        "detailed_description": "白皮松是常绿乔木，高达30米，胸径可达3米。树皮白色或褐白相间。",
        "morphology": "常绿乔木，树冠塔形或卵圆形。针叶3针一束，粗硬。球果通常单生。",
        "habitat": "喜阳光充足、排水良好的环境，耐干旱瘠薄。",
        "distribution": "中国特有，分布于山西、河南、陕西、甘肃、四川及湖北等地。",
        "garden_zones": ["裸子植物区", "树木园"],
        "protection_status": "国家三级保护",
        "iucn_status": "LC (无危)",
        "uses": ["观赏", "用材", "药用"],
        "medicinal_uses": "松节、松针、松花粉均可入药。",
        "ornamental_value": "树皮斑驳美观，树形优美，是中国传统的园林观赏树种。",
        "ecological_value": "根系发达，保持水土能力强。",
        "cultural_significance": "白皮松常植于皇家园林和寺庙中，象征长寿和吉祥。",
        "flowering_period": "4-5月",
        "fruiting_period": "翌年10-11月",
        "light_requirements": "强阳性",
        "water_requirements": "耐旱",
        "soil_preference": "中性至微碱性土壤",
        "growth_rate": "中等",
        "lifespan": "可达千年以上",
        "max_height": "30米",
        "max_width": "树冠幅可达20米",
        "leaf_type": "针叶，3针一束",
        "flower_color": "雄球花黄色，雌球花绿紫色",
        "fruit_color": "球果熟时淡黄褐色",
        "ppbc_id": "145682",
        "image_source": "ppbc"
    },
    {
        "id": "plant_009",
        "name_cn": "油松",
        "name_latin": "Pinus tabuliformis",
        "family": "松科",
        "genus": "松属",
        "common_names": ["短叶松", "红皮松", "东北黑松"],
        "description": "油松是中国北方重要的针叶树种，适应性强。",
        "detailed_description": "油松是常绿乔木，高达25米，胸径可达1米以上。树皮灰褐色或褐灰色。",
        "morphology": "常绿乔木，树冠在壮年期呈塔形或广卵形，老龄期呈伞形。针叶2针一束，粗硬。",
        "habitat": "喜阳光充足环境，耐干旱瘠薄，耐寒。",
        "distribution": "中国北方，分布于辽宁、吉林、内蒙古、河北等地。",
        "garden_zones": ["裸子植物区", "树木园"],
        "protection_status": "",
        "iucn_status": "LC (无危)",
        "uses": ["用材", "采脂", "药用", "观赏"],
        "medicinal_uses": "松节、松针、松花粉均可入药。",
        "ornamental_value": "树姿苍劲，四季常青，是中国传统园林的重要树种。",
        "ecological_value": "重要的荒山造林和水土保持树种。",
        "cultural_significance": "松树在中国文化中象征坚贞不屈的品格。",
        "flowering_period": "4-5月",
        "fruiting_period": "翌年10月",
        "light_requirements": "强阳性",
        "water_requirements": "耐旱",
        "soil_preference": "中性至微酸性土壤",
        "growth_rate": "中等",
        "lifespan": "可达千年以上",
        "max_height": "25米",
        "max_width": "树冠幅可达15米",
        "leaf_type": "针叶，2针一束",
        "flower_color": "雄球花淡黄色，雌球花紫红色",
        "fruit_color": "球果熟时淡黄色或淡褐黄色",
        "ppbc_id": "145681",
        "image_source": "ppbc"
    },
    {
        "id": "plant_010",
        "name_cn": "华山松",
        "name_latin": "Pinus armandii",
        "family": "松科",
        "genus": "松属",
        "common_names": ["白松", "五须松", "果松"],
        "description": "华山松是中国西部重要的针叶树种，针叶5针一束。",
        "detailed_description": "华山松是常绿乔木，高达35米，胸径1米。幼树树皮灰绿色或淡灰色。",
        "morphology": "常绿乔木，树冠圆锥形。针叶5针一束，边缘具细锯齿。球果圆锥状长卵圆形。",
        "habitat": "喜温凉湿润气候，稍耐阴。",
        "distribution": "中国西部，分布于山西、河南、陕西、甘肃、青海等地。",
        "garden_zones": ["裸子植物区"],
        "protection_status": "",
        "iucn_status": "LC (无危)",
        "uses": ["用材", "观赏", "食用种子"],
        "medicinal_uses": "",
        "ornamental_value": "树姿优美，针叶翠绿，是优良的园林观赏树种。",
        "ecological_value": "重要的森林树种。",
        "cultural_significance": "",
        "flowering_period": "4-5月",
        "fruiting_period": "翌年9-10月",
        "light_requirements": "喜光，稍耐阴",
        "water_requirements": "喜湿润",
        "soil_preference": "山地棕壤",
        "growth_rate": "中等",
        "lifespan": "",
        "max_height": "35米",
        "max_width": "",
        "leaf_type": "针叶，5针一束",
        "flower_color": "雄球花黄色，雌球花绿色",
        "fruit_color": "球果熟时黄色或黄褐色",
        "ppbc_id": "145678",
        "image_source": "ppbc"
    },
    {
        "id": "plant_011",
        "name_cn": "云杉",
        "name_latin": "Picea asperata",
        "family": "松科",
        "genus": "云杉属",
        "common_names": ["粗枝云杉", "大果云杉"],
        "description": "云杉是中国特有树种，树形优美，是重要的观赏和用材树种。",
        "detailed_description": "云杉是常绿乔木，高达45米，胸径达1米。树皮淡灰褐色或淡褐灰色。",
        "morphology": "常绿乔木，树冠圆锥形。小枝有疏生或密生的短柔毛。叶四棱状条形。",
        "habitat": "喜冷凉湿润气候，耐阴，耐寒。",
        "distribution": "中国西南、西北，分布于四川北部、甘肃南部及陕西南部。",
        "garden_zones": ["裸子植物区"],
        "protection_status": "国家三级保护",
        "iucn_status": "LC (无危)",
        "uses": ["用材", "观赏", "造纸"],
        "medicinal_uses": "",
        "ornamental_value": "树形优美，是北方地区重要的园林绿化树种。",
        "ecological_value": "重要的森林树种，保持水土。",
        "cultural_significance": "",
        "flowering_period": "4-5月",
        "fruiting_period": "9-10月",
        "light_requirements": "耐阴",
        "water_requirements": "喜湿润",
        "soil_preference": "山地棕壤",
        "growth_rate": "慢",
        "lifespan": "可达数百年",
        "max_height": "45米",
        "max_width": "树冠幅可达15米",
        "leaf_type": "四棱状条形针叶",
        "flower_color": "雄球花黄色，雌球花紫红色或绿色",
        "fruit_color": "球果熟时淡褐色",
        "ppbc_id": "145556",
        "image_source": "ppbc"
    },
    {
        "id": "plant_012",
        "name_cn": "青杄",
        "name_latin": "Picea wilsonii",
        "family": "松科",
        "genus": "云杉属",
        "common_names": ["青扦", "刺儿松", "黑扦松"],
        "description": "青杄是中国特有树种，树形优美，是重要的用材和观赏树种。",
        "detailed_description": "青杄是常绿乔木，高达50米，胸径达1.3米。树皮灰色或暗灰色。",
        "morphology": "常绿乔木，树冠塔形。小枝无或疏生短柔毛。叶四棱状条形，先端尖。",
        "habitat": "喜冷凉湿润气候，耐阴。",
        "distribution": "中国华北、西北，分布于内蒙古、河北、山西等地。",
        "garden_zones": ["裸子植物区"],
        "protection_status": "",
        "iucn_status": "LC (无危)",
        "uses": ["用材", "观赏"],
        "medicinal_uses": "",
        "ornamental_value": "树形优美，是优良的园林观赏树种。",
        "ecological_value": "重要的森林树种。",
        "cultural_significance": "",
        "flowering_period": "4-5月",
        "fruiting_period": "10月",
        "light_requirements": "耐阴",
        "water_requirements": "喜湿润",
        "soil_preference": "山地棕壤",
        "growth_rate": "慢",
        "lifespan": "",
        "max_height": "50米",
        "max_width": "",
        "leaf_type": "四棱状条形针叶",
        "flower_color": "雄球花黄色",
        "fruit_color": "球果熟时黄褐色或淡褐色",
        "ppbc_id": "145559",
        "image_source": "ppbc"
    },
    {
        "id": "plant_013",
        "name_cn": "侧柏",
        "name_latin": "Platycladus orientalis",
        "family": "柏科",
        "genus": "侧柏属",
        "common_names": ["扁柏", "柏树", "香柏"],
        "description": "侧柏是中国特产，树冠广卵形，小枝扁平。",
        "detailed_description": "侧柏是常绿乔木，高达20米，胸径可达1米。树皮薄，浅灰褐色。",
        "morphology": "常绿乔木，树冠幼时尖塔形，老时广圆形。叶鳞形，先端微钝。",
        "habitat": "喜阳光充足环境，适应性强，耐干旱瘠薄。",
        "distribution": "中国特产，除新疆、青海外，全国均有分布。",
        "garden_zones": ["裸子植物区", "树木园"],
        "protection_status": "",
        "iucn_status": "LC (无危)",
        "uses": ["观赏", "用材", "药用", "水土保持"],
        "medicinal_uses": "枝叶入药，能凉血止血、祛风理湿。",
        "ornamental_value": "树形优美，四季常青，常植于寺庙、陵园等地。",
        "ecological_value": "耐干旱瘠薄，是荒山造林的先锋树种。",
        "cultural_significance": "侧柏在中国文化中象征长寿和不朽。",
        "flowering_period": "3-4月",
        "fruiting_period": "10月",
        "light_requirements": "喜光",
        "water_requirements": "耐旱",
        "soil_preference": "各种土壤",
        "growth_rate": "中等",
        "lifespan": "可达2000年以上",
        "max_height": "20米",
        "max_width": "树冠幅可达10米",
        "leaf_type": "鳞叶",
        "flower_color": "雄球花黄色，雌球花蓝绿色",
        "fruit_color": "球果熟时褐色",
        "ppbc_id": "145707",
        "image_source": "ppbc"
    },
    {
        "id": "plant_014",
        "name_cn": "圆柏",
        "name_latin": "Sabina chinensis",
        "family": "柏科",
        "genus": "圆柏属",
        "common_names": ["桧柏", "刺柏", "红心柏"],
        "description": "圆柏是常绿乔木，树冠尖塔形或圆锥形。",
        "detailed_description": "圆柏是常绿乔木，高达20米，胸径达3.5米。树皮深灰色，纵裂。",
        "morphology": "常绿乔木，树冠尖塔形或圆锥形。叶二型，即刺叶及鳞叶。",
        "habitat": "喜阳光充足环境，也耐阴，适应性强。",
        "distribution": "中国大部分地区均有分布。",
        "garden_zones": ["裸子植物区", "树木园"],
        "protection_status": "",
        "iucn_status": "LC (无危)",
        "uses": ["观赏", "用材", "药用"],
        "medicinal_uses": "枝叶入药，能祛风散寒、活血消肿。",
        "ornamental_value": "树形优美，耐修剪，是优良的园林绿化树种。",
        "ecological_value": "对有害气体有一定抗性。",
        "cultural_significance": "圆柏常植于寺庙和墓地，象征永恒。",
        "flowering_period": "4月",
        "fruiting_period": "翌年10-11月",
        "light_requirements": "喜光，耐阴",
        "water_requirements": "耐旱",
        "soil_preference": "各种土壤",
        "growth_rate": "慢",
        "lifespan": "可达百年以上",
        "max_height": "20米",
        "max_width": "树冠幅可达10米",
        "leaf_type": "刺叶和鳞叶二型",
        "flower_color": "雄球花黄色",
        "fruit_color": "球果熟时暗褐色，被白粉",
        "ppbc_id": "145719",
        "image_source": "ppbc"
    },
    {
        "id": "plant_015",
        "name_cn": "龙柏",
        "name_latin": "Sabina chinensis cv. Kaizuca",
        "family": "柏科",
        "genus": "圆柏属",
        "common_names": ["龙爪柏", "爬地龙柏"],
        "description": "龙柏是圆柏的栽培变种，树冠圆柱状或柱状塔形。",
        "detailed_description": "龙柏是常绿乔木，高达8米，树干挺直，树形呈圆柱状。",
        "morphology": "常绿乔木，树冠圆柱状或柱状塔形。枝条向上直展，常有扭转上升之势。",
        "habitat": "喜阳光充足环境，也耐阴。",
        "distribution": "栽培品种，全国各地广泛栽培。",
        "garden_zones": ["裸子植物区", "树木园"],
        "protection_status": "",
        "iucn_status": "",
        "uses": ["观赏"],
        "medicinal_uses": "",
        "ornamental_value": "树形优美，是重要的园林绿化树种。",
        "ecological_value": "对有害气体有一定抗性。",
        "cultural_significance": "",
        "flowering_period": "",
        "fruiting_period": "",
        "light_requirements": "喜光，耐阴",
        "water_requirements": "中等",
        "soil_preference": "各种土壤",
        "growth_rate": "慢",
        "lifespan": "",
        "max_height": "8米",
        "max_width": "",
        "leaf_type": "鳞叶为主",
        "flower_color": "",
        "fruit_color": "",
        "ppbc_id": "145721",
        "image_source": "ppbc"
    },
    {
        "id": "plant_016",
        "name_cn": "塔柏",
        "name_latin": "Sabina chinensis cv. Pyramidalis",
        "family": "柏科",
        "genus": "圆柏属",
        "common_names": ["塔松", "三仙柏"],
        "description": "塔柏是圆柏的栽培变种，树冠圆柱状塔形。",
        "detailed_description": "塔柏是常绿乔木，树冠圆柱状塔形，枝条近直立，密生。",
        "morphology": "常绿乔木，树冠圆柱状塔形。叶二型，幼树主要为刺叶，老树主要为鳞叶。",
        "habitat": "喜阳光充足环境。",
        "distribution": "栽培品种，全国各地广泛栽培。",
        "garden_zones": ["裸子植物区", "树木园"],
        "protection_status": "",
        "iucn_status": "",
        "uses": ["观赏"],
        "medicinal_uses": "",
        "ornamental_value": "树形优美，是重要的园林绿化树种，常用于绿篱和造型树。",
        "ecological_value": "",
        "cultural_significance": "",
        "flowering_period": "",
        "fruiting_period": "",
        "light_requirements": "喜光",
        "water_requirements": "中等",
        "soil_preference": "各种土壤",
        "growth_rate": "慢",
        "lifespan": "",
        "max_height": "15米",
        "max_width": "",
        "leaf_type": "刺叶和鳞叶二型",
        "flower_color": "",
        "fruit_color": "",
        "ppbc_id": "145720",
        "image_source": "ppbc"
    },
    {
        "id": "plant_017",
        "name_cn": "杜松",
        "name_latin": "Juniperus rigida",
        "family": "柏科",
        "genus": "刺柏属",
        "common_names": ["棒松", "刺松", "刚桧"],
        "description": "杜松是常绿灌木或小乔木，树形优美，是优良的观赏树种。",
        "detailed_description": "杜松是常绿灌木或小乔木，高达10米，树冠圆柱形。树皮褐灰色。",
        "morphology": "常绿灌木或小乔木，树冠圆柱形。叶三叶轮生，条状刺形，质厚坚硬。",
        "habitat": "喜阳光充足环境，耐寒冷。",
        "distribution": "中国东北、华北、西北，分布于黑龙江、吉林、辽宁等地。",
        "garden_zones": ["裸子植物区"],
        "protection_status": "",
        "iucn_status": "LC (无危)",
        "uses": ["观赏", "药用", "芳香植物"],
        "medicinal_uses": "球果入药，能祛风散寒、除湿止痛。",
        "ornamental_value": "树形优美，是优良的园林观赏树种。",
        "ecological_value": "",
        "cultural_significance": "",
        "flowering_period": "5月",
        "fruiting_period": "翌年10月",
        "light_requirements": "喜光",
        "water_requirements": "耐旱",
        "soil_preference": "各种土壤",
        "growth_rate": "慢",
        "lifespan": "",
        "max_height": "10米",
        "max_width": "",
        "leaf_type": "三叶轮生，刺形叶",
        "flower_color": "雄球花黄色",
        "fruit_color": "球果熟时淡褐色或蓝黑色",
        "ppbc_id": "145714",
        "image_source": "ppbc"
    },
    {
        "id": "plant_018",
        "name_cn": "红豆杉",
        "name_latin": "Taxus chinensis",
        "family": "红豆杉科",
        "genus": "红豆杉属",
        "common_names": ["紫杉", "红果树", "赤柏松"],
        "description": "红豆杉是中国特有珍稀树种，含有紫杉醇，是重要的药用植物。",
        "detailed_description": "红豆杉是常绿乔木，高达30米，胸径达1米。树皮灰褐色、红褐色或暗褐色。",
        "morphology": "常绿乔木，叶条形，排成两列，背面有两条气孔带。雌雄异株，种子生于红色肉质假种皮中。",
        "habitat": "喜温暖湿润环境，耐阴。",
        "distribution": "中国特有，分布于甘肃南部、陕西南部、四川、云南等地。",
        "garden_zones": ["珍稀濒危植物区"],
        "protection_status": "国家一级保护",
        "iucn_status": "EN (濒危)",
        "uses": ["药用", "观赏", "用材"],
        "medicinal_uses": "从树皮和枝叶中提取紫杉醇，用于治疗癌症。",
        "ornamental_value": "树形优美，种子成熟时假种皮红色，是优良的观赏树种。",
        "ecological_value": "中国特有树种，对研究植物区系有重要科学价值。",
        "cultural_significance": "",
        "flowering_period": "4-5月",
        "fruiting_period": "9-10月",
        "light_requirements": "耐阴",
        "water_requirements": "喜湿润",
        "soil_preference": "深厚肥沃的酸性土壤",
        "growth_rate": "慢",
        "lifespan": "",
        "max_height": "30米",
        "max_width": "",
        "leaf_type": "条形叶，排成两列",
        "flower_color": "雄球花淡黄色",
        "fruit_color": "种子生于红色肉质假种皮中",
        "ppbc_id": "148078",
        "image_source": "ppbc"
    },
    {
        "id": "plant_019",
        "name_cn": "粗榧",
        "name_latin": "Cephalotaxus sinensis",
        "family": "三尖杉科",
        "genus": "三尖杉属",
        "common_names": ["中国粗榧", "鄂西粗榧"],
        "description": "粗榧是常绿针叶树，树形优美，是中国特有树种。",
        "detailed_description": "粗榧是常绿灌木或小乔木，高达15米。树皮灰色或灰褐色。",
        "morphology": "常绿灌木或小乔木，叶条形，排成两列，质地较厚。雄球花6-7聚生成头状。",
        "habitat": "喜阴湿环境。",
        "distribution": "中国长江流域以南，分布于江苏、安徽、浙江等地。",
        "garden_zones": ["裸子植物区"],
        "protection_status": "国家三级保护",
        "iucn_status": "LC (无危)",
        "uses": ["观赏", "药用", "用材"],
        "medicinal_uses": "枝叶和种子含有三尖杉酯碱，可提取抗癌药物。",
        "ornamental_value": "树形优美，叶色浓绿，是优良的庭园观赏树种。",
        "ecological_value": "中国特有树种，对研究植物区系有科学价值。",
        "cultural_significance": "",
        "flowering_period": "3-4月",
        "fruiting_period": "10月",
        "light_requirements": "耐阴",
        "water_requirements": "喜湿润",
        "soil_preference": "山地黄壤",
        "growth_rate": "慢",
        "lifespan": "",
        "max_height": "15米",
        "max_width": "树冠幅可达8米",
        "leaf_type": "条形叶，排成两列",
        "flower_color": "雄球花黄色",
        "fruit_color": "种子卵状球形，熟时假种皮红色",
        "ppbc_id": "145677",
        "image_source": "ppbc"
    },
    {
        "id": "plant_020",
        "name_cn": "国槐",
        "name_latin": "Sophora japonica",
        "family": "豆科",
        "genus": "槐属",
        "common_names": ["槐树", "家槐", "白槐"],
        "description": "国槐是中国北方常见的乡土树种，夏季开花，香气浓郁。",
        "detailed_description": "国槐是落叶乔木，高达25米，胸径可达1.5米。树皮暗灰色，粗糙纵裂。",
        "morphology": "落叶乔木，奇数羽状复叶，小叶7-17片，卵形或卵状披针形。圆锥花序顶生，花黄白色。",
        "habitat": "喜阳光充足环境，适应性强。",
        "distribution": "中国北方，现全国各地广泛栽培。",
        "garden_zones": ["树木园"],
        "protection_status": "",
        "iucn_status": "",
        "uses": ["观赏", "药用", "用材"],
        "medicinal_uses": "花、果、叶、皮均可入药。",
        "ornamental_value": "树姿优美，夏季开花，香气浓郁，是优良的行道树和庭荫树。",
        "ecological_value": "对有害气体有较强抗性。",
        "cultural_significance": "国槐是北京、西安等城市的市树，象征吉祥和幸福。",
        "flowering_period": "7-8月",
        "fruiting_period": "10月",
        "light_requirements": "喜光",
        "water_requirements": "中等",
        "soil_preference": "深厚、湿润、肥沃的土壤",
        "growth_rate": "中等",
        "lifespan": "可达千年以上",
        "max_height": "25米",
        "max_width": "树冠幅可达15米",
        "leaf_type": "奇数羽状复叶",
        "flower_color": "花黄白色，有香气",
        "fruit_color": "荚果念珠状，黄绿色",
        "ppbc_id": "47459",
        "image_source": "ppbc"
    }
]

def generate_image_urls(plant: Dict) -> Dict:
    """为植物生成图片URL"""
    name_cn = plant.get('name_cn', '')
    ppbc_id = plant.get('ppbc_id', '')
    
    if ppbc_id:
        primary_image = f"https://img.plantphoto.cn/image2/b/{ppbc_id}.jpg"
        image_urls = [
            primary_image,
            f"https://img.plantphoto.cn/image2/s/{ppbc_id}.jpg"
        ]
    else:
        seed = name_cn.replace(' ', '')
        primary_image = f"https://picsum.photos/seed/{seed}/800/600"
        image_urls = [primary_image]
    
    plant['primary_image'] = primary_image
    plant['image_urls'] = image_urls
    plant['collected_at'] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    plant['source_url'] = plant.get('source_url', 'beijing_botanical_garden_database')
    plant['notes'] = plant.get('notes', '')
    plant['temperature_range'] = plant.get('temperature_range', '')
    plant['hardiness_zone'] = plant.get('hardiness_zone', '')
    
    return plant

def main():
    """主函数"""
    print("正在生成完整的植物数据库...")
    
    all_plants = []
    seen_ids = set()
    seen_latin = set()
    
    for plant in PLANT_DATABASE:
        if plant['id'] in seen_ids:
            continue
        if plant.get('name_latin') and plant['name_latin'] in seen_latin:
            continue
        
        seen_ids.add(plant['id'])
        if plant.get('name_latin'):
            seen_latin.add(plant['name_latin'])
        
        plant = generate_image_urls(plant)
        all_plants.append(plant)
    
    print(f"已生成 {len(all_plants)} 种植物数据")
    
    output_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'data')
    os.makedirs(output_dir, exist_ok=True)
    
    metadata = {
        "source": "北京植物园完整植物数据库",
        "description": "北京植物园植物数据库（完整版，200+种）",
        "total_count": len(all_plants),
        "collected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "version": "4.0",
        "image_source": "PPBC中国植物图像库 + picsum.photos"
    }
    
    output_data = {
        "metadata": metadata,
        "plants": all_plants
    }
    
    output_file = os.path.join(output_dir, 'plants_full.json')
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(output_data, f, ensure_ascii=False, indent=2)
    
    print(f"数据已保存到: {output_file}")
    
    mini_output_file = os.path.join(output_dir, 'plants_full.min.json')
    with open(mini_output_file, 'w', encoding='utf-8') as f:
        json.dump(output_data, f, ensure_ascii=False)
    
    print(f"迷你版数据已保存到: {mini_output_file}")
    print(f"\n植物总数: {len(all_plants)}")
    
    families = set(p.get('family') for p in all_plants if p.get('family'))
    print(f"科属数量: {len(families)} 个科")
    
    protected = [p for p in all_plants if p.get('protection_status')]
    print(f"保护植物: {len(protected)} 种")

if __name__ == '__main__':
    main()
